FROM n8nio/n8n:2.21.4

ENV N8N_LISTEN_ADDRESS=0.0.0.0 \
    N8N_PROTOCOL=http \
    N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true \
    N8N_SECURE_COOKIE=false

EXPOSE 5678

ENTRYPOINT []

CMD ["sh", "-c", "export N8N_PORT=${PORT:-${N8N_PORT:-5678}} && exec n8n start"]
